name: STRONG
channels:
    - anaconda
    - conda-forge
    - bioconda
    - r
dependencies:
    - bioconda::snakemake=7.24.0
    - anaconda::python=3.7.13
    - bioconda::metabat2=2.15
    - anaconda::biopython=1.78
    - bioconda::bowtie2=2.4.5
    - bioconda::samtools=1.6
    - bioconda::prodigal=2.6.3
    - bioconda::blast=2.16.0
    - bioconda::concoct=1.1.0
    - bioconda::mafft=7.520
    - bioconda::trimal=1.5.0
    - bioconda::fasttree=2.1.11
    - bioconda::gfapy=1.2.3
    - anaconda::future=0.18.2
    - bioconda::pysam=0.16.0.1
    - conda-forge::pygam=0.9.0
    - anaconda::statsmodels=0.11.1
    - conda-forge::pathos=0.3.2
    - conda-forge::ete3=3.1.2
    - bioconda::bedtools=2.31.1
    - anaconda::cmake=3.14.0
    - anaconda::matplotlib=3.3.2
    - anaconda::numpy=1.16.0
    - anaconda::pandas>=0.24.0
    - anaconda::networkx>=2.4
    - anaconda::scikit-learn=0.23.2
    - bioconda::bam-readcount=1.0.1
    - anaconda::seaborn=0.11.2
    - anaconda::poppler=0.81.0
    - bioconda::emboss=6.6.0
    - conda-forge::r-base=4.0.3
    - conda-forge::r-ggplot2=3.3.2
    - conda-forge::r-ape=5.4
    - conda-forge::r-getopt=1.20.3
    - conda-forge::r-reshape=0.8.8
    - conda-forge::r-reshape2=1.4.4
    - conda-forge::r-stringr=1.4.0
    - conda-forge::r-rvcheck=0.1.8
    - bioconda::gtdbtk=2.3.2
    - bioconda::bioconductor-ggtree=2.2.1
    - bioconda::bioconductor-treeio=1.12.0
    - conda-forge::r-wesanderson=0.3.6
    - anaconda::libiconv=1.16
    - conda-forge::gfortran_impl_linux-64=9.5.0
    - conda-forge::gfortran_linux-64=9.5.0
    - anaconda::libgfortran-ng=7.3.0
    - conda-forge::xorg-libxt=1.1.5
